name: scroll_infinity
description: ScrollInfinity is a Flutter package that provides a widget with infinite scrolling and paginated loading support, making it easier to build dynamic and endless listings.
version: 0.5.2
homepage: https://github.com/dariomatias-dev/scroll_infinity
repository: https://github.com/dariomatias-dev/scroll_infinity
issue_tracker: https://github.com/dariomatias-dev/scroll_infinity/issues
topics:
  - infinite-scroll
  - pagination
  - listview
  - lazy-loading
  - scroll

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
